### ISSUE TITLE
EZMicrophone delegate methods are not called in some cases

### ISSUE THREAD

**Issue by ghulammustafa** [syedhali/EZAudio#89] opened 2014-09-09 07:44 UTC
In some cases, the EZMicrophone class is successfully instantiated, but the delegate callbacks are not received -- and as a result the audio plot is not generated. Has anyone else encountered this problem?

**Comment by syedhali** [comment] 2015-06-29 03:11
Don't know if this is still an issue with the new EZMicrophone 0.1.0 release. I'm going to close this ticket because I'm not able to reproduce.

**Closed by syedhali** 2015-06-29 03:11 UTC
