### ISSUE TITLE
Error: Failed to fill complex buffer in float converter ('insz') on iPhone 6S and 6S Plus

### ISSUE THREAD

**Issue by hyd00** [syedhali/EZAudio#246] opened 2015-11-24 13:45 UTC
Everything is working great on iPhone 4S, 5 / 5S, 6 and 6 Plus , but when trying to use audioplot on iPhone 6S and 6S Plus, following error is coming:

`Error: Failed to fill complex buffer in float converter ('insz')`

I have also implemented https://github.com/syedhali/EZAudio/issues/173 solution, but no luck

Please help!

**Comment by davidwadge** [comment] 2015-11-30 12:04
Also having the same issue on 6S.

**Comment by Danbana** [comment] 2015-11-30 20:49
Hooboy... also seeing this crash. No bueno!

**Comment by smspence** [comment] 2015-12-15 06:44
Any updates on this issue?
I am now receiving this crash and error on an iPhone 6 since updating to iOS 9.2:
```
Error: Failed to fill complex buffer in float converter ('insz')
```

It worked fine before on iOS 8.4 through 9.1

**Comment by snyuryev** [comment] 2015-12-15 07:18
9.2 - same for me

**Comment by syedhali** [comment] 2015-12-15 07:20
Hey guys seems like the EZAudioFloatConverter is bugging out for buffer sizes that aren't 512 or 1024. I'll need to look into that component and see what I'm doing wrong :/

**Comment by koooootake** [comment] 2015-12-17 14:11
9.2 - same for me (iPhone 5S)

**Comment by dsmelov** [comment] 2015-12-18 12:59
The source of this problem is in EZAudioFloatConverterCallback (EZAudioFloatConverter.m). This function should update ioData->mBuffers[0].mDataByteSize. For 16bit audio stream it will look like 
ioData->mBuffers[0].mDataByteSize = *ioNumberDataPackets * sizeof(short);

**Comment by garsdle** [comment] 2015-12-18 22:17
What is really strange is that the FFT example seems unaffected by this bug?

**Comment by hyd00** [comment] 2015-12-19 09:52
^Exactly! The examples provided work perfect on ALL the devices (including 6S and 6S Plus)

**Comment by BrandonZacharie** [comment] 2015-12-20 02:24
I haven't tested the examples. I simply rebuilt my own project. The problem seems to have gone away on real devices but I still get crashes in the simulator. ¯\_(ツ)_/¯

**Comment by patriksharma** [comment] 2015-12-23 12:20
any update on this ? 

I'm facing crash in Iphone 6s and IOS 9.2

**Comment by trkfabi** [comment] 2016-01-03 22:51
I don't know if it is related to what you guys are discussing, but I was getting this same error line when I tried to change the sample rate from 44100 to 8000 (for a guitar tuner app).

What I did was basically use this line of code to initialize the mic instance with a different sample rate:

```
   AudioStreamBasicDescription inputFormat = [EZAudioUtilities monoFloatFormatWithSampleRate:SAMPLE_RATE];
    self.microphone = [EZMicrophone microphoneWithDelegate:self withAudioStreamBasicDescription: inputFormat];
```
if I used ```double const SAMPLE_RATE = 8000.0f;``` I'd get the error but it works with ```double const SAMPLE_RATE = 11025.0f;``` 

11025 is pretty enough for what I want so...

**Comment by rbarbish** [comment] 2016-01-04 04:24
Solution - @trkfabi 's code snippet led to my solution of this crash, which occurred on launch / microphone instantiation. And only starting occurring upon upgrading to iOS 9.2 for the majority of the users of my app.

I changed the microphone instantiation code from:
'''
self.microphone = [EZMicrophone microphoneWithDelegate:self];
'''
to
'''
AudioStreamBasicDescription inputFormat = [EZAudioUtilities monoFloatFormatWithSampleRate:44100.0f];
    self.microphone = [EZMicrophone microphoneWithDelegate:self withAudioStreamBasicDescription: inputFormat];
'''

**Comment by kenzukan** [comment] 2016-01-04 05:50
I faced this issue when app have multi instances of EZMicrophone(). (iOS9.2 and iPhone5S, 6S)
I solved this issue by using `EZMicrophone.sharedMicrophone()` instead of `EZMicrophone()`.

**Comment by Xinaction** [comment] 2016-01-06 02:15
@rbarbish @kenzukan  I'm no luck with your code. like @syedhali  said, buffer sizes that aren't 512 or 1024, in my device 6S(9.2) buffer size 940...crash..

**Comment by Xinaction** [comment] 2016-01-06 03:28
It's so odd that demo without any error and buffer size is 1024 with iPhone6S 9.2

**Comment by snyuryev** [comment] 2016-01-06 17:34
@rbarbish Thank you very much! Works for me!

**Comment by Xinaction** [comment] 2016-01-07 03:10
@snyuryev do you try iPhone6S iOS9.2?, all my devices are ok except 6S(iOS9.2)

**Comment by Xinaction** [comment] 2016-01-10 09:43
@syedhali  I found the cause of the problem. The internal speaker on the iPhone 6S models only support a sample rate of 48kHz while previous iPhone models supported a collection of sample rates.  
1024 * (44100/48000) = 940.8, Micphone buffer size in EZAudio is 940 or 941 that crash.
I cann't understand why the demo didn't crash. I had fix my code with 48k.

**Comment by lususvir** [comment] 2016-01-11 07:33
@rbarbish solution worked for me. I have an iPad mini running iOS 9.2, never had an issue. I had an iPhone 4s running iOS 7.X, never had an issue. Upgraded my iPhone 4s to iOS 9.2, started having the issue every time I started recording.

**Comment by cameronmccord2** [comment] 2016-01-13 17:52
@syedhali solution fixed our problem. On the iOS 9.2 with iPhone 6s Plus we were having the "Error: Failed to fill complex buffer in float converter ('insz')" error. We fixed it by specifying the microphone sample rate at 48000. But, doing that then broke it for our iOS 9.2 iPhone 5s and caused the same error. We fixed it by adding this piece of code:

```swift
if UIDevice.currentDevice().modelName.containsString("iPhone 6s") {
    let inputFormat = EZAudioUtilities.monoFloatFormatWithSampleRate(48000.0)
    microphone = EZMicrophone(microphoneDelegate: self, withAudioStreamBasicDescription: inputFormat)
}else{
    microphone = EZMicrophone(microphoneDelegate: self)
}
```

Caveat: This may break when the iPhone 7 comes out because of how we are detecting the iPhone version.

**Comment by subinkk08** [comment] 2016-01-18 11:53
Failed to write audio data to recorded audio file ('insz') i got this error iphone 5  iOS 9.2 .

**Comment by vineethvijayan** [comment] 2016-01-19 11:05
Any update on above? Its showing issue in iOS 9.2, with multiple devices

**Comment by vineethvijayan** [comment] 2016-01-20 09:34
Any update on this issue? Same issue in 9.2.1 too

**Comment by syedhali** [comment] 2016-01-24 09:38
Hey everyone, I was able to reproduce this issue by setting the preferred sample rate to 48000 (default on iPhone 6s + iPhone 6s+) and found out the issue was that the scratch AudioBufferList structures' mDataByteSize property used in the EZMicrophone and the EZAudioFloatConverter was not being set property.

This issue is fixed as of the 1.1.4 release. I'm closing this for now, but let me know if this is still an issue after updating.

**Closed by syedhali** 2016-01-24 09:38 UTC

**Comment by kajensen** [comment] 2016-02-27 23:21
I can reproduce this on 6s when fetching audio from an EZMicrophone and transitioning the output from iphone speaker to apple tv airplay.

**Comment by ShrikantCoder** [comment] 2019-08-20 07:21
Any updates on this issue?
I am now receiving this crash and error on an iPhone X since updating to iOS 13 (beta):

Error: Failed to fill complex buffer in float converter ('insz')
It worked fine before iOS 13.

**Comment by sugite** [comment] 2019-08-24 05:56
@ShrikantCoder  same to me, do you have any solution ?

**Comment by mahadshahib** [comment] 2019-09-14 12:39
any update on the solution I have same issue on iPhone X running iOS 13 beta @ShrikantCoder

**Comment by mahadshahib** [comment] 2019-09-14 12:40
@sugite any solution ?

**Comment by m1entus** [comment] 2019-09-16 14:00
+1

**Comment by dengini** [comment] 2019-09-17 01:30
For iOS 13 it will return the same error if you are using a sample rate other than 44100. It will crash with:
`Error: Failed to fill complex buffer in float converter ('insz')`

The simple fix is to set the shared audio session sample rate equal to value you specify in EZMircophone. I can go more into detail if you want.

```
let audioSession = AVAudioSession.sharedInstance()
try audioSession.setCategory(.playAndRecord, mode: .default, options: [])
try audioSession.setPreferredSampleRate(16000)
try audioSession.setActive(true, options: [])

// convert mic input to format required for asr
var monoStreamFormat:AudioStreamBasicDescription = AudioStreamBasicDescription()
monoStreamFormat.mSampleRate = 16000
...
self.microphone = EZMicrophone(delegate: self, with: monoStreamFormat, startsImmediately: false)
```

**Comment by mahadshahib** [comment] 2019-09-17 21:53
Thanks for your solution i didnt test it yet on my problem but one thing i’ve been noticed is that every case problem here involves ezmicrophone but in my case iam not even using microphone my case is playing some avaudio files using ezaudioplayer what do you think? @dengini

**Comment by dengini** [comment] 2019-09-18 03:30
@mahadshahib Without having a sample project it's difficult to say.  I will describe what I did to fix my issue. It may help.

Set a breakpoint in EZAudioUtilities.m (Line 539).  See what functions are called before it.
`fprintf(stderr, "Error: %s (%s)\n", operation, errorString);`

In my case I noticed it was EZAudioFloatConvert.m
```
- (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
                    withNumberOfFrames:(UInt32)frames
                        toFloatBuffers:(float **)buffers
                    packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions

// print out frame info for debugging
NSLog(@"frames:%d, mBytesPerFrame:%d, mDataByteSize:%d", frames, self.info->inputFormat.mBytesPerFrame, frames * self.info->inputFormat.mBytesPerFrame);
```
Connected 2 phones. 1 iOS 12 and iOS 13 and compared the values.  I noticed that mBytesPerFrame was 4 on iOS 13 and 2 on iOS 12. This was the cause of my problem.

I traced the call to EZMicrophone.m setup function (Line 251).
`self.info->inputFormat.mSampleRate = [[AVAudioSession sharedInstance] sampleRate];`

The above pulled the value from shareInstance instead of value I passed. The phone default was 44100 instead of 16000. This caused the buffer size mismatch.

Setting the shareInstance sample rate to match the EZMicrophone value fixed my issue.
`try audioSession.setPreferredSampleRate(16000)`

**Comment by mahadshahib** [comment] 2019-09-18 09:55
thanks again i test this solution and it didn't work for me . I have a very sample project with my problem I made a zip file here https://github.com/mahadshahib/PandoraPlayerTest1 can you take a quick look at my project and help me in it thank you. @dengini

**Comment by mahadshahib** [comment] 2019-09-18 12:19
@dengini

            try AVAudioSession.sharedInstance().setPreferredSampleRate(8000)

also 
this line changes sample rate on iOS 12 simulator but it has to effect on iOS 13 iphone x

**Comment by ashishkeshan** [comment] 2019-09-23 04:23
does anyone have a solution for iOS 13?

**Comment by dengini** [comment] 2019-09-23 21:31
@mahadshahib Last week was very busy. I just took a look at the code you posted. I was able to get it to build using AudioKit 4.9.  Unfortunately the sample code you uploaded has other issues.  I didn't get a crash on EZAudio.

Crash line (PandoraPlayer.swift):
`commandCenter.togglePlayPauseCommand.addTarget(self, action:   #selector(onPlay))`

Error (crash from addTarget above):
```
2019-09-23 14:28:39.797487-0700 PandoraPlayerTest[2967:779908] *** Assertion failure in -[MPRemoteCommand addTarget:action:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/MediaPlayer/MobileMusicPlayer-4017.101.15/SDK/MPRemoteCommand.m:134
2019-09-23 14:28:39.798702-0700 PandoraPlayerTest[2967:779908] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported action method signature. Must return MPRemoteCommandHandlerStatus or take a completion handler as the second argument.'
*** First throw call stack:
(0x1b01a098c 0x1afec90a4 0x1b00a2d1c 0x1b04d88f4 0x1bc4f2fa0 0x1045b8b6c 0x1045b4620 0x1045b4200 0x1045b15c8 0x1045b1210 0x1045b1250 0x1b3b9c560 0x1b3ba1070 0x1b3ba1478 0x1b3bb6ba8 0x1b3baf9b8 0x1b3bb1338 0x1b3bb38a4 0x1b3bb3da0 0x1b3bb37f4 0x1b3bb3a5c 0x10459b424 0x10459b49c 0x1b41aede0 0x1b3bf2bb4 0x1b3bf2f18 0x1b3bf1f34 0x1b41e8104 0x1b41e9444 0x1b41c5e84 0x1b423d43c 0x1b423f998 0x1b423880c 0x1b011e7e0 0x1b011e738 0x1b011ded0 0x1b011901c 0x1b01188bc 0x1b9f7d328 0x1b41ada70 0x1045a52dc 0x1affa3460)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ashishkeshan** [comment] 2019-09-23 21:40
Did you test it on a physical device running iOS 13?

**Comment by dengini** [comment] 2019-09-23 21:41
Physical device

**Comment by ashishkeshan** [comment] 2019-09-23 22:47
Perhaps this bug is fixed in iOS 13.1 then. I am still running into this issue on my physical device running iOS 13.

**Comment by dengini** [comment] 2019-09-23 23:18
Same crash on XS running 13.0. After click button, the player form crashes on present.  The same error as reported above. I can't see audio playback error.  My pod info for comparison.

```
PODS:
  - AudioKit (4.9):
    - AudioKit/Core (= 4.9)
    - AudioKit/UI (= 4.9)
  - AudioKit/Core (4.9)
  - AudioKit/UI (4.9):
    - AudioKit/Core
  - SPStorkController (1.7.9)
```

**Comment by ashishkeshan** [comment] 2019-09-23 23:20
Did you comment out the `updateCommandCenter()` at line 730 of PandoraPlayer.swift?

**Comment by dengini** [comment] 2019-09-23 23:29
@ashishkeshan commenting out that line worked. The player loaded. Unfortunately I can't help you.  You are using AudioKit instead of including EZAudio directly. AudioKit only includes the header files not the source. I can't trace the code into EZAudio files to see the values.

**Comment by ashishkeshan** [comment] 2019-09-23 23:32
Did you get the same error when the player loaded though? (Error: Failed to fill complex buffer in float converter ('insz')). I am trying to determine if this is simply an iOS 13 bug that will get patched in iOS 13.1, or if I should spend more time investigating the issue as you mentioned.

**Comment by dengini** [comment] 2019-09-23 23:36
@ashishkeshan Yes. I was able to replicate the buffer error on 13.0 & 13.1 after commenting out that function.  Like said in my edited comment above. I can't really do much without source code for AudioKit included. Need to be able to see buffer values to determine cause of mismatch.
`Error: Failed to fill complex buffer in float converter ('insz')`

**Comment by dengini** [comment] 2019-09-23 23:52
Ideally if you can create a sample project just including EZAudio with audio playback.  This will simplify things quite a bit. EZAudio cocoapod is deprecated but comes with full source when include it. Makes it easy to trace through code and view values. With AudioKit it just a binary so can't really debug. Unless you remove the Podfile and include fill source and project file for AudioKit.

**Comment by ashishkeshan** [comment] 2019-09-24 02:45
Hey @dengini -- I just set up a sample project here: https://github.com/ashishkeshan/TestEZAudioBug

I am trying to set the sample rate to 48000, but for some reason, the value is not getting updated. The sample rate is always 44100 no matter what code I add, and this is causing the buffer sizes to be 940 or 941 frames resulting in the mismatch. Do you think you could take a look at the project to see if there are any fixes that you can think of? Thanks!

**Comment by mahadshahib** [comment] 2019-09-24 06:20
@ashishkeshan @dengini 
I was able to reset sample rate to what ever I wANT with audiukit global setting using AKSetting.sample but not matter how I change sample rate it still crashes on physical device I think we have to email audio kit developers and let them know maybe they would fix it

**Comment by dengini** [comment] 2019-09-24 20:40
From looking at the new sample project. The audio player is a bit different than Microphone.  This I what I noticed so far. I will try look again this evening if I have more free time. FYI: around Xcode 10 it stopped auto rebuilding the pods when changes are made. If you modify EZAudio code you need to do a clean and rebuild app each time.

EZAudioFloatConverter.m
```
- (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
                    withNumberOfFrames:(UInt32)frames
                        toFloatBuffers:(float **)buffers
                    packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions
{
	...
	[EZAudioUtilities checkResult:AudioConverterFillComplexBuffer(self.info->converterRef,
                                                                      EZAudioFloatConverterCallback,
                                                                      audioBufferList,
                                                                      &frames,
                                                                      self.info->floatAudioBufferList,
                                                                      packetDescriptions ? packetDescriptions : self.info->packetDescriptions)
                            operation:"Failed to fill complex buffer in float converter"];

```

In this function it appears to work for the first 5 calls and fails on the 6th.  So far the only thing that stands out is the 5th buffer was slightly smaller at 3760, then 6th was back to 3764. I am not certain this is the cause, but something to look into.
```
2019-09-24 13:37:57.303360-0700 Project10[759:104811] frames:941, mBytesPerFrame:4, mDataByteSize:3764
2019-09-24 13:37:57.324460-0700 Project10[759:104811] frames:941, mBytesPerFrame:4, mDataByteSize:3764
2019-09-24 13:37:57.345794-0700 Project10[759:104811] frames:941, mBytesPerFrame:4, mDataByteSize:3764
2019-09-24 13:37:57.367112-0700 Project10[759:104811] frames:941, mBytesPerFrame:4, mDataByteSize:3764
2019-09-24 13:37:57.388501-0700 Project10[759:104811] frames:940, mBytesPerFrame:4, mDataByteSize:3760
2019-09-24 13:37:57.409782-0700 Project10[759:104811] frames:941, mBytesPerFrame:4, mDataByteSize:3764
Error: Failed to fill complex buffer in float converter ('insz')
```

**Comment by mahadshahib** [comment] 2019-09-28 09:00
@dengini @ashishkeshan @ShrikantCoder @sugite any solution yet?

**Comment by desmeit** [comment] 2019-09-30 07:58
same issue here.

**Comment by tetujin** [comment] 2019-09-30 08:24
As a temporal solution for avoiding the forced exit, you can comment out the `exit(-1);` in the `+ (void)checkResult:(OSStatus)result operation:(const char *)operation` method in `EZAudioUtilities.m` . The solution is working now on my device, but that is not a fundamental solution for the issue, and also I have not checked the side-effect of the modification.

**Comment by IlyaBlinov** [comment] 2019-10-01 10:05
Hi. This worked for me: In AudioKit I changed in file EZOutput.m  constant : Float64 const EZOutputDefaultSampleRate     = 48000.0f. By default this constant is 44100.0f

**Comment by IlyaBlinov** [comment] 2019-10-03 11:25
Guys, I set in file EZOutput.m constant : Float64 const EZOutputDefaultSampleRate = 44100.0f and changed: - (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
withNumberOfFrames:(UInt32)frames toFloatBuffers:(float **)buffers
packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions in EZAudioFloatConverter.m. I changed :
[EZAudioUtilities checkResult:AudioConverterFillComplexBuffer(self.info->converterRef,
EZAudioFloatConverterCallback,
audioBufferList,
&frames,
self.info->floatAudioBufferList,
packetDescriptions ? packetDescriptions : self.info->packetDescriptions)
operation:"Failed to fill complex buffer in float converter"]; To
OSStatus status = AudioConverterFillComplexBuffer(self.info->converterRef,
EZAudioFloatConverterCallback,
audioBufferList,
&frames,
self.info->floatAudioBufferList,
packetDescriptions ? packetDescriptions : self.info->packetDescriptions);

    NSLog(@"status = %d",(int)status);
Status have the value = 1768846202 sometimes. May be there are drops, I don't know. But it works for me

**Comment by mahadshahib** [comment] 2019-10-08 13:04
2019-10-08 16:31:49.607832+0330 Music Time[2986:623624] kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=3763, mMaxFramesPerSlice=1156 
new issue! it works with your solution but when I lock device playback stops and I get this error on console any idea? @IlyaBlinov @tetujin @desmeit @dengini @ashishkeshan

**Comment by dengini** [comment] 2019-10-08 23:50
For the EZOutput fix I wouldn't recommend just changing the constant from 44100 to 48000. This could cause other issues on different OS or devices.

remove const from EZOutputDefaultSampleRate in .h & .m.

EZOutput.m (setup or init) - assign value to shared session value.
`EZOutputDefaultSampleRate = [[AVAudioSession sharedInstance] sampleRate];`

**Comment by dengini** [comment] 2019-10-09 02:01
@mahadshahib 

If you look at the logs, when goes into background mode the bytes size is quadrupled. The number of frames jumps from 1024 to 4096.
```
2019-10-08 18:51:39.467494-0700 Project10[1975:446490] frames:1024, mBytesPerFrame:4, mDataByteSize:4096
2019-10-08 18:51:39.468726-0700 Project10[1975:446490] kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=4096, mMaxFramesPerSlice=1156
2019-10-08 18:51:39.468935-0700 Project10[1975:446490] frames:4096, mBytesPerFrame:4, mDataByteSize:16384
```

Not sure the consequences of this, but it seems to fix the problem. Change the following in EZOutput.m:
```
UInt32  const EZOutputMaximumFramesPerSlice = 4096;
to
UInt32  const EZOutputMaximumFramesPerSlice = 1024;

```

cause:
```
//
// Set maximum frames per slice to 4096 to allow playback during
// lock screen (iOS only?)
//
UInt32 maximumFramesPerSlice = EZOutputMaximumFramesPerSlice;
[EZAudioUtilities checkResult:AudioUnitSetProperty(self.info->mixerNodeInfo.audioUnit,
                                                   kAudioUnitProperty_MaximumFramesPerSlice,
                                                   kAudioUnitScope_Global,
                                                   0,
                                                   &maximumFramesPerSlice,
                                                   sizeof(maximumFramesPerSlice))
                    operation:"Failed to set maximum frames per slice on mixer node"];
```

That will prevent the crash. The audio will pause and resume when you unlock device.

**Comment by mahadshahib** [comment] 2019-10-09 13:06
@dengini I want audio to continue playing on lock screen I can prevent the crash but I can't prevent audio pause on lock screen

**Comment by harshshah1992** [comment] 2019-10-17 12:41
Hello Guys, i have tried all the above solution but it's still crashing. Can you please provide proper solution?

**Comment by desmeit** [comment] 2019-10-18 11:48
Same issue here. I tried 48000.0f but its still not working.

**Comment by dengini** [comment] 2019-10-18 15:32
You need to be a bit more specific about your settings. Either provide a sample project or changes to the above from @ashishkeshan.

Set the default sample rate before active:
```
try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: [.mixWithOthers,.allowAirPlay])
try AVAudioSession.sharedInstance().setPreferredSampleRate(48000) // or 41000
try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)

self.audioFile = EZAudioFile(url: url)
```

Remove the hard coded 441000 from EZOutput. This seems to solve my issues.  
Remove the const in EZOutput.h & .m. Then set to the default session value in setup.
```
Float64 const EZOutputDefaultSampleRate     = 44100.0f;
to (remove const)
Float64 EZOutputDefaultSampleRate     = 44100.0f;

- (void)setup
{
    EZOutputDefaultSampleRate = [[AVAudioSession sharedInstance] sampleRate];
    ...
```

For these to take effect you might have to initialize the EZAudio after the audio session set active. (See the self.audioFile = EZAudioFile... above). This way EZAudio initializes after your session value changes.

**Comment by desmeit** [comment] 2019-10-18 15:42
`- (void) initMic {
    [self configureAudioSession];
    AudioStreamBasicDescription audioStreamBasicDescription = [EZAudioUtilities monoFloatFormatWithSampleRate:16000];
    audioStreamBasicDescription.mFormatID = kAudioFormatLinearPCM;
    audioStreamBasicDescription.mSampleRate = 16000;
    audioStreamBasicDescription.mFramesPerPacket = 1;
    audioStreamBasicDescription.mBytesPerPacket = 2;
    audioStreamBasicDescription.mBytesPerFrame = 2;
    audioStreamBasicDescription.mChannelsPerFrame = 1;
    audioStreamBasicDescription.mBitsPerChannel = 16;
    audioStreamBasicDescription.mFormatFlags = kAudioFormatFlagIsSignedInteger | kAudioFormatFlagsNativeEndian | kAudioFormatFlagIsPacked;
    audioStreamBasicDescription.mReserved = 0;

    NSArray *inputs = [EZAudioDevice inputDevices];
    [self.microphone setDevice:[inputs lastObject]];
    self.microphone = [EZMicrophone microphoneWithDelegate:self withAudioStreamBasicDescription:audioStreamBasicDescription];
    [self.microphone startFetchingAudio];
}`

EZAudio works with Snowboy. How can I change the settings below?
https://github.com/Kitt-AI/snowboy

**Comment by dengini** [comment] 2019-10-19 10:30
@desmeit EZMicrophone works without any code changes. You just need to initialize things in the proper order.  Here are the 16K settings I use while connecting to an ASR service.

```
do {
        let audioSession = AVAudioSession.sharedInstance()
        try audioSession.setCategory(.playAndRecord, mode: .default, options: [])
        try audioSession.setPreferredSampleRate(16000)
        try audioSession.setActive(true, options: [])
            
        // convert mic input to format required for asr
        var monoStreamFormat:AudioStreamBasicDescription = AudioStreamBasicDescription()
        monoStreamFormat.mSampleRate = 16000.0
        monoStreamFormat.mFormatID = kAudioFormatLinearPCM
        monoStreamFormat.mFormatFlags = kAudioFormatFlagIsSignedInteger | kAudioFormatFlagsNativeEndian | kAudioFormatFlagIsPacked;
        monoStreamFormat.mFramesPerPacket = 1
        monoStreamFormat.mChannelsPerFrame = 1
        monoStreamFormat.mBytesPerFrame = monoStreamFormat.mChannelsPerFrame * 2
        monoStreamFormat.mBytesPerPacket = monoStreamFormat.mFramesPerPacket * monoStreamFormat.mBytesPerFrame
        monoStreamFormat.mBitsPerChannel = 16
        monoStreamFormat.mReserved = 0
            
        self.microphone = EZMicrophone(delegate: self, with: monoStreamFormat, startsImmediately: false)](url)
```

Notes:
1) Audio session setPreferredSampleRate needs to be set before set active.
2) EZMicrophone has to be initialized after the audio session changes. EZMicrophone uses the shared Sample Rate value on init. If you initialize EZMicrophone prior to the audio session sample rate change, it will use the default value and cause buffer errors.

**Comment by desmeit** [comment] 2019-10-21 06:49
Thank you so much. It is working.

**Comment by mahadshahib** [comment] 2019-10-21 13:13
@dengini hello again your solution actually worked for me but I still get this error
`kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=3764, mMaxFramesPerSlice=1156`
I checked EZOutput.m file for the solution it says set EZOutputMaximumFramesPerSlice to 4096 to allow playback during lock screen I did this but I think it failed to set it and I still get the same error and I can't get playback during lock screen any idea?

**Comment by eqiihuu** [comment] 2019-12-12 01:20
> Thank you so much. It is working.

Hi @desmeit , I'm using the same Snowboy code as yours, and setPreferredSampleRate before setActive. However the same error still exists. Could you help check what's wrong with the following code?

CODE:
 ```
- (void) configureAudioSession
{
    AVAudioSession *session = [AVAudioSession sharedInstance];
    [session setActive:NO error:NULL];
    [session setCategory:AVAudioSessionCategoryRecord error:NULL];
    [session setPreferredSampleRate:16000 error:NULL];
    [session setActive:YES error:NULL];
}
- (void) initMic {
    [self configureAudioSession];
    
    AudioStreamBasicDescription audioStreamBasicDescription = [EZAudioUtilities monoFloatFormatWithSampleRate:16000];
    audioStreamBasicDescription.mFormatID = kAudioFormatLinearPCM;
    audioStreamBasicDescription.mSampleRate = 16000;
    audioStreamBasicDescription.mFramesPerPacket = 1;
    audioStreamBasicDescription.mBytesPerPacket = 2;
    audioStreamBasicDescription.mBytesPerFrame = 2;
    audioStreamBasicDescription.mChannelsPerFrame = 1;
    audioStreamBasicDescription.mBitsPerChannel = 16;
    audioStreamBasicDescription.mFormatFlags = kAudioFormatFlagIsSignedInteger | kAudioFormatFlagsNativeEndian | kAudioFormatFlagIsPacked;
    audioStreamBasicDescription.mReserved = 0;
    
    NSArray *inputs = [EZAudioDevice inputDevices];
    [self.microphone setDevice:[inputs lastObject]];
    self.microphone = [EZMicrophone microphoneWithDelegate:self withAudioStreamBasicDescription:audioStreamBasicDescription];
    [self.microphone startFetchingAudio];
}
```

ERROR:
`Error: Failed to fill complex buffer in float converter ('insz')`

**Comment by desmeit** [comment] 2019-12-12 09:04
@eqiihuu do you test it on a real device or in simulator?
In simulator the error still exists but on real device it is working for me.

**Comment by eqiihuu** [comment] 2019-12-13 22:37
> @eqiihuu do you test it on a real device or in simulator?
> In simulator the error still exists but on real device it is working for me.

I tested it in the simulator. I haven't got a real device for testing yet. In the simulator, I can successfully run the demo by applying this fix (https://github.com/AudioKit/AudioKit/issues/1873#issuecomment-539357011). However, this is not a final solution since it's continuously doing the reset.
